### ISSUE TITLE
Educacional - Front 

### ISSUE THREAD

**Issue by WellingtonLFaria** [Grupo-Syntax-Squad/Tupan#31]
### **_Oque fazer_**:
Criar página "Educacional" para que as crianças de escolas, ou quaisquer outras pessoas aprendam os conceitos para medições de temperatura, como funcionam os equipamentos das estações, etc.
### **_Restrições_**: 
precisa ser uma página lúdica e com textos de fácil entendimento, contando com imagens ilustrativas e até vídeos se for o caso.
### **_Falha_**: 
não há falhas.
### **_Conteúdo_**: 

- Textos sobre escalas termométricas;
- Imagens ilustrativas;
- Implementar um Quiz (pode ser interessante);
- Como preservar o ambiente e evitar desastres meteorológicos;
- Vídeos ou GIFS mostrando o funcionamento;
- Textos sobre os equipamentos de medição (barômetro, pluviômetro, etc...);

--------------------------------------------------------------------------------------------------------------------------------------------

### **_Aceitação_**:
- [x] Página com o conteúdo presente;
- [x] Página é lúdica;

--------------------------------------------------------------------------------------------------------------------------------------------

### **_Apoio_**:
Figma

**Comment by b4hia** [comment]
pagina feita aguardando review do pr
